alias jslint='jsl -nologo -nocontext -nofilelisting -nosummary -process'
alias fixmacdns='dscacheutil -flushcache'
alias fact="curl -s randomfunfacts.com | grep strong | cut -d\> -f5- | cut -d\< -f1"
alias critic='svnperl | xargs perlcritic -p ~/.perlcriticrc.local --statistics --verbose "%f:%l:%c:[%p] %m\n"'
alias svngrep='find . -xdev -type f -not -path "*.svn/*" -not -path "*.git/*" -print0 2>/dev/null | xargs -0 grep --color=auto -InH'
alias histgrep='find ~/.history/ -type f -print0 2>/dev/null | xargs -0 grep --color=auto -InH'
alias lintperl="svnperl | xargs -I{} perl -cIlib {}"
alias lockup='light-locker-command --lock'
alias ll='ls -alF --color=auto'
alias emacs="emacs -nw"
alias grep="grep --color=auto"
alias benice="nice -n19 ionice -c 3"
alias ..="cd .."
alias lintpuppet='find . -type f -name "*.pp" -exec puppet parser validate {} + && puppet-lint --fail-on-warnings modules || figlet FAIL'
alias gitgc='nice -n19 ionice -c 3 git repack -a -d -f --depth=1000 --window=500'
alias gitdev='git log --oneline develop..HEAD'
alias gitdevp='git log -p develop..HEAD'
alias gitdevd='git diff develop..HEAD'
alias mousefix='gsettings set org.gnome.settings-daemon.plugins.cursor active false'
alias qreset='echo -e "\0033\0143"'
alias lrmax='lrzip -vv -Uz -N 19 -L 9'
alias xzmax='xz -9evv --lzma2=dict=128MiB,lc=4,lp=0,pb=2,mode=normal,nice=273,mf=bt4,depth=1024'
alias startipy='screen -S jupyter -Q select . || screen -dmS jupyter jupyter notebook --notebook-dir=$HOME/working --ip=0.0.0.0 --no-browser && sleep 2 && juptmp=$(mktemp) && screen -S jupyter -p 0 -X hardcopy "$juptmp" && grep -om1 http.\* "$juptmp" | sed s/0\.0\.0\.0/rmoore.vdesk.cloud.aurora.tech/g && rm "$juptmp" && unset juptmp'
alias nukedocker='ps -a -q | xargs --no-run-if-empty docker rm;docker image list -q | grep -v 7c09e61e9035 | xargs --no-run-if-empty docker rmi'
alias jenkinsbackup='rsync -a --rsync-path="sudo rsync" --info=progress2 jenkins-master:/var/lib/jenkins/ ~/working/jenkins/'
alias updateqa='ssh -t qabox ./update-qa.sh'
alias brewup='brew update;brew upgrade;brew cask outdated | cut -d\  -f1 | xargs brew cask reinstall'
alias ecrlogin='eval "$(aws ecr get-login --no-include-email)"'
alias awslogin='bazel run //cloud/terraform:aws_auth -- login'
alias k8slogin='bazel run //cloud/terraform:aws_auth -- k8s'
alias ubuntu='docker run --rm -it --mount type=bind,source=${HOME}/working,target=/working ubuntu:focal'
alias spacelift-container='docker run --rm -it public.ecr.aws/spacelift/runner-terraform:latest'
alias youtube-dl='youtube-dl --format '\''22/bestvideo[height<=?720][ext=mp4]+bestaudio[ext=m4a]'\'''
alias tfgo='terraform init && terraform get && terraform plan -out plan.out'
alias tflock='terraform init -upgrade -lock=false -backend=false && terraform providers lock -platform=linux_amd64 && terraform providers lock -platform=linux_arm64 && terraform providers lock -platform=darwin_arm64'
alias ident='figlet -w $COLUMNS -r $USER | lolcat -p 0.3'
alias fedrate='curl -s https://fred.stlouisfed.org/data/MORTGAGE15US.txt | tail -1 | awk '\''{print "Fed rate for " $1 " is " $2}'\'''
alias googsync='LOG_LEVEL=debug time bazel run //cloud/terraform:sso_admin -- sync-google --test-org --save-temp'
alias awsfind='2>/dev/null bazel run //cloud/terraform:acct_mgr find'
alias spaceliftdns='dig @8.8.8.8 +noall +answer +dnssec aurora-tech.app.spacelift.io'
alias ubsan='bazel test --config clang --config ubsan -c dbg'
alias tsan='bazel test --config clang --config tsan -c dbg'
alias asan='bazel test --config clang --config asan -c dbg'
alias Xubsan='bazel test --config clang --config ubsan -c dbg --runs_per_test=100'
alias Xtsan='bazel test --config clang --config tsan -c dbg --runs_per_test=100'
alias Xasan='bazel test --config clang --config asan -c dbg --runs_per_test=100'
alias kick-crypt='gpg -ear rmoore@aurora.tech <<< "hello" | gpg -qd > /dev/null'
alias webserver='screen -dmS webserver python3 -m http.server 8080'
alias goodiotop='sudo bash -c "sysctl kernel.task_delayacct=1 && iotop -o -d5 -P; sysctl kernel.task_delayacct=0"'
alias pynt='bazel test --config=python_next --config=intel-cuda --cache_test_results=no --build_tests_only --test_tag_filters=av_py_target,-broken-python-next,-local,-no-buildkite,-gui,-integration,-requires-network --test_lang_filters=py'
# alias bkpynt='bazel --nohome_rc test --trim_test_configuration --//build:in_build_ci_flag=True --test_summary=terse --test_output=errors --noshow_progress --config=python_next --config=intel-cuda --build_tag_filters=av_py_target,-broken-python-next,-packaging --config=buildkite_output --profile=profile-test.gz --build_event_binary_file=build-events-test.bin --config=ci --build_tests_only --test_timeout=30,120,300,900 --test_size_filters=small,medium,large --test_tag_filters=av_py_target,-broken-python-next,-local,-no-buildkite,-gui,-integration,-requires-network'
alias tagbroken='buildozer "add tags broken-python-next"'
alias untagbroken='buildozer "remove tags broken-python-next"'
alias bkpynt='$(./tools/bin/build_plan.par --command=test python-next) > >(ts %Y-%m-%d:%H:%M:%.S | tee stdout.$(date +%Y-%m-%dT%H.%M).txt) 2> >(ts %Y-%m-%d:%H:%M:%.S | tee stderr.$(date +%Y-%m-%dT%H.%M).txt)'
alias bkpyntY='$(./tools/bin/build_plan.par --command=test --command_flags=--noremote_accept_cached  python-next) > >(ts %Y-%m-%d:%H:%M:%.S | tee stdout.txt) 2> >(ts %Y-%m-%d:%H:%M:%.S | tee stderr.txt)'
alias bkpyntX='$(./tools/bin/build_plan.par --command=test --command_flags=--remote_executor=,--remote_cache=  python-next-all-tests) > >(ts %Y-%m-%d:%H:%M:%.S | tee stdout.txt) 2> >(ts %Y-%m-%d:%H:%M:%.S | tee stderr.txt)'
alias freezedeps='bazel run //common/python/pip:freeze_dependencies -- python_37 python_310 python_aarch64 --yes_to_prompt'
alias molly='bazel run //tools/monorepo/molly:molly'
alias repro='bazel test --config=python_next --config=intel-cuda --cache_test_results=no --build_tests_only //experimental/rmoore/pynext:torch_repro_generated_tests'

alias docker='podman'
